package p11

import (
	"errors"
	"sync"

	"github.com/battlestarcap/pkcs11"
)

// Session represents a PKCS#11 session.
type Session interface {
	// Login logs into the token as a regular user. Note: According to PKCS#11,
	// logged-in state is a property of an application, rather than a session, but
	// you can only log in via a session. Keep this in mind when using multiple
	// sessions on the same token. Logging in to a token in any session will log
	// in all sessions on that token, and logging out will do the same. This is
	// particularly relevant for private keys with CKA_ALWAYS_AUTHENTICATE set
	// (like Yubikeys in PIV mode). See
	// https://github.com/letsencrypt/pkcs11key/blob/master/key.go for an example
	// of managing login state with a mutex.
	Login(pin string) error
	// Login logs into the token as the security officer.
	LoginSecurityOfficer(pin string) error
	// Logout logs out all sessions from the token (see Login).
	Logout() error
	// Close closes the session.
	Close() error

	// CreateObject creates an object on the token with the given attributes.
	CreateObject(template []*pkcs11.Attribute) (Object, error)
	// FindObject finds a single object in the token that matches the attributes in
	// the template. It returns error if there is not exactly one result, or if
	// there was an error during the find calls.
	FindObject(template []*pkcs11.Attribute) (Object, error)
	// FindObjects finds any objects in the token matching the template.
	FindObjects(template []*pkcs11.Attribute) ([]Object, error)
	// GenerateKeyPair generates a public/private key pair. It takes
	// GenerateKeyPairRequest instead of individual arguments so that attributes for
	// public and private keys can't be accidentally switched around.
	GenerateKeyPair(request GenerateKeyPairRequest) (*KeyPair, error)
	// GenerateRandom returns random bytes generated by the token.
	GenerateRandom(length int) ([]byte, error)

	// InitPIN initialize's the normal user's PIN.
	InitPIN(pin string) error
	// SetPIN modifies the PIN of the logged-in user. "old" should contain the
	// current PIN, and "new" should contain the new PIN to be set.
	SetPIN(old, new string) error
}

type SessionImpl struct {
	sync.Mutex
	Ctx    *pkcs11.Ctx
	Handle pkcs11.SessionHandle
}

func (s *SessionImpl) FindObject(template []*pkcs11.Attribute) (Object, error) {
	objects, err := s.FindObjects(template)
	if err != nil {
		return Object{}, nil
	}
	if len(objects) > 1 {
		return Object{}, errors.New("too many objects matching template")
	}
	return objects[0], nil
}

func (s *SessionImpl) FindObjects(template []*pkcs11.Attribute) ([]Object, error) {
	s.Lock()
	defer s.Unlock()
	if err := s.Ctx.FindObjectsInit(s.Handle, template); err != nil {
		return nil, err
	}

	var results []Object
	for {
		ObjectHandles, _, err := s.Ctx.FindObjects(s.Handle, 100)
		if err != nil {
			_ = s.Ctx.FindObjectsFinal(s.Handle)
			return nil, err
		} else if len(ObjectHandles) == 0 {
			break
		}
		i := len(results)
		results = append(results, make([]Object, len(ObjectHandles))...)
		for j, ObjectHandle := range ObjectHandles {
			results[i+j] = Object{
				Session:      s,
				ObjectHandle: ObjectHandle,
			}
		}
	}
	if err := s.Ctx.FindObjectsFinal(s.Handle); err != nil {
		return nil, err
	} else if len(results) == 0 {
		return nil, errors.New("no objects found")
	}
	return results, nil
}

func (s *SessionImpl) Close() error {
	s.Lock()
	defer s.Unlock()
	return s.Ctx.CloseSession(s.Handle)
}

func (s *SessionImpl) Login(pin string) error {
	return s.login(pkcs11.CKU_USER, pin)
}

func (s *SessionImpl) LoginSecurityOfficer(pin string) error {
	return s.login(pkcs11.CKU_SO, pin)
}

func (s *SessionImpl) login(userType uint, pin string) error {
	s.Lock()
	defer s.Unlock()
	return s.Ctx.Login(s.Handle, userType, pin)
}

func (s *SessionImpl) Logout() error {
	s.Lock()
	defer s.Unlock()
	return s.Ctx.Logout(s.Handle)
}

func (s *SessionImpl) GenerateRandom(length int) ([]byte, error) {
	s.Lock()
	defer s.Unlock()
	return s.Ctx.GenerateRandom(s.Handle, length)
}

func (s *SessionImpl) CreateObject(template []*pkcs11.Attribute) (Object, error) {
	s.Lock()
	defer s.Unlock()
	oh, err := s.Ctx.CreateObject(s.Handle, template)
	if err != nil {
		return Object{}, err
	}
	return Object{
		Session:      s,
		ObjectHandle: oh,
	}, nil
}

func (s *SessionImpl) InitPIN(pin string) error {
	s.Lock()
	defer s.Unlock()
	return s.Ctx.InitPIN(s.Handle, pin)
}

func (s *SessionImpl) SetPIN(old, new string) error {
	s.Lock()
	defer s.Unlock()
	return s.Ctx.SetPIN(s.Handle, old, new)
}

// KeyPair contains two Objects: one for a public key and one for a private key.
// It represents these as PublicKey and PrivateKey types so they can by used for
// appropriate cryptographic operations.
type KeyPair struct {
	Public  PublicKey
	Private PrivateKey
}

// GenerateKeyPairRequest contains the fields used to generate a key pair.
type GenerateKeyPairRequest struct {
	Mechanism            pkcs11.Mechanism
	PublicKeyAttributes  []*pkcs11.Attribute
	PrivateKeyAttributes []*pkcs11.Attribute
}

func (s *SessionImpl) GenerateKeyPair(request GenerateKeyPairRequest) (*KeyPair, error) {
	s.Lock()
	defer s.Unlock()
	pubHandle, privHandle, err := s.Ctx.GenerateKeyPair(s.Handle,
		[]*pkcs11.Mechanism{&request.Mechanism},
		request.PublicKeyAttributes,
		request.PrivateKeyAttributes)
	if err != nil {
		return nil, err
	}
	return &KeyPair{
		Public: PublicKey(Object{
			Session:      s,
			ObjectHandle: pubHandle,
		}),
		Private: PrivateKey(Object{
			Session:      s,
			ObjectHandle: privHandle,
		}),
	}, nil
}
